import type { HeaderConfig, FooterConfig, PanelConfig } from '../types/reframe-types'
import { FONT_MAP } from '../types/reframe-types'

export interface CodegenOptions {
  templateName: string
  headerConfig: HeaderConfig
  footerConfig: FooterConfig
  panels: Record<string, PanelConfig>
  themeKey?: string
  layoutJson?: any
}

/**
 * Generates a standalone, production-ready React TSX component
 * that renders the client deliverable using pure Tailwind CSS Flex/Grid.
 * Faithfully reproduces the Dockview layout tree with ZERO dependencies
 * on Dockview, sashes, or builder chrome.
 */
export function generateStandaloneClientTsx(options: CodegenOptions): string {
  const { templateName, headerConfig, footerConfig, panels, layoutJson } = options

  const panelList = Object.values(panels)
  const fontFamily = FONT_MAP[headerConfig.fontFamily] || FONT_MAP.inter

  // Format panel data and layout tree as clean JSON to embed directly in the component
  const embeddedPanelsJson = JSON.stringify(panelList, null, 2)
  const embeddedGridJson = layoutJson?.grid?.root
    ? JSON.stringify(layoutJson.grid, null, 2)
    : 'null'

  return `import React, { useState } from 'react'
import {
  Layers,
  Activity,
  BarChart3,
  Terminal,
  Sparkles,
  Shield,
  Zap,
  RefreshCw,
  Search,
  ArrowUpRight,
  TrendingUp,
  TrendingDown,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Info
} from 'lucide-react'
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid
} from 'recharts'

/**
 * =====================================================================
 * CLIENT DELIVERABLE: ${templateName.toUpperCase()}
 * Generated by Reframe Studio
 * Pure React + Tailwind CSS (Zero Dockview Runtime)
 * =====================================================================
 */

interface WidgetItem {
  id: string
  title: string
  widgetType: string
  widgetProps: Record<string, any>
}

const BAKED_PANELS: WidgetItem[] = ${embeddedPanelsJson}
const LAYOUT_GRID: any = ${embeddedGridJson}

function DockviewNodeRenderer({ node, orientation }: { node: any; orientation: 'HORIZONTAL' | 'VERTICAL' }) {
  if (!node) return null

  if (node.type === 'leaf') {
    const activeViewId = node.data?.activeView || (node.data?.views && node.data.views[0])
    const panel = BAKED_PANELS.find((p) => p.id === activeViewId)
    if (!panel) return null

    return (
      <div className="w-full h-full rounded-xl bg-zinc-900/50 border border-zinc-800/80 overflow-hidden shadow-sm flex flex-col hover:border-zinc-700/80 transition-all backdrop-blur-sm min-h-[220px]">
        <div className="px-4 py-3 border-b border-zinc-800 flex items-center justify-between bg-zinc-900/80 shrink-0">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-indigo-500" />
            <h2 className="text-sm font-semibold text-zinc-100">{panel.title}</h2>
          </div>
          <span className="text-[10px] uppercase font-mono tracking-wider text-zinc-500 px-2 py-0.5 rounded bg-zinc-800/60">
            {panel.widgetType}
          </span>
        </div>
        <div className="p-4 flex-1 overflow-auto">
          <WidgetRenderer panel={panel} />
        </div>
      </div>
    )
  }

  if (node.type === 'branch') {
    const isHorizontal = orientation === 'HORIZONTAL'
    const nextOrientation = isHorizontal ? 'VERTICAL' : 'HORIZONTAL'
    const children = Array.isArray(node.data) ? node.data : []

    return (
      <div className={\`w-full h-full flex gap-4 min-w-0 min-h-0 \${isHorizontal ? 'flex-col md:flex-row' : 'flex-col'}\`}>
        {children.map((child: any, idx: number) => {
          const flexGrow = typeof child.size === 'number' && child.size > 0 ? child.size : 1
          return (
            <div key={idx} className="flex-1 min-w-0 min-h-0 flex flex-col" style={{ flex: \`\${flexGrow} 1 0%\` }}>
              <DockviewNodeRenderer node={child} orientation={nextOrientation} />
            </div>
          )
        })}
      </div>
    )
  }

  return null
}

export const ClientDashboard: React.FC = () => {
  return (
    <div
      className="w-full min-h-screen bg-zinc-950 text-zinc-100 flex flex-col font-sans select-none"
      style={{ fontFamily: '${fontFamily}' }}
    >
      {/* ── CLIENT HEADER FRAMING ───────────────────────────────── */}
      ${
        headerConfig.visible
          ? `<header className="border-b border-zinc-800 bg-zinc-950/90 backdrop-blur-md px-6 py-3 flex items-center justify-between gap-4 sticky top-0 z-30">
        <div className="flex items-center gap-3 min-w-0">
          ${
            headerConfig.showLogo
              ? `<div className="w-8 h-8 rounded-lg bg-indigo-600/20 border border-indigo-500/40 flex items-center justify-center text-indigo-400 shrink-0">
            <Layers className="w-4 h-4" />
          </div>`
              : ''
          }
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-bold tracking-tight text-white">${headerConfig.title}</h1>
              ${
                headerConfig.badge
                  ? `<span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/30">
                ${headerConfig.badge}
              </span>`
                  : ''
              }
            </div>
            ${headerConfig.subtitle ? `<p className="text-xs text-zinc-400 font-normal">${headerConfig.subtitle}</p>` : ''}
          </div>
        </div>

        <div className="flex items-center gap-2">
          ${headerConfig.actions
            .map(
              (act) => `
          <button
            key="${act.id}"
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-900 border border-zinc-800 hover:border-zinc-700 text-zinc-200 transition-colors"
          >
            <span>${act.label}</span>
          </button>`
            )
            .join('')}
        </div>
      </header>`
          : '/* Header hidden */'
      }

      {/* ── MAIN DASHBOARD GRID (ZERO DOCKVIEW) ──────────────────── */}
      <main className="flex-1 p-6 overflow-y-auto max-w-7xl mx-auto w-full flex flex-col min-h-0">
        {LAYOUT_GRID?.root ? (
          <div className="w-full h-full min-h-0 flex-1 flex flex-col">
            <DockviewNodeRenderer node={LAYOUT_GRID.root} orientation={LAYOUT_GRID.orientation || 'HORIZONTAL'} />
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 flex-1">
            {BAKED_PANELS.map((panel) => (
              <div
                key={panel.id}
                className="rounded-xl bg-zinc-900/50 border border-zinc-800/80 overflow-hidden shadow-sm flex flex-col"
              >
                <div className="px-4 py-3 border-b border-zinc-800 flex items-center justify-between bg-zinc-900/80">
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-indigo-500" />
                    <h2 className="text-sm font-semibold text-zinc-100">{panel.title}</h2>
                  </div>
                  <span className="text-[10px] uppercase font-mono tracking-wider text-zinc-500 px-2 py-0.5 rounded bg-zinc-800/60">
                    {panel.widgetType}
                  </span>
                </div>
                <div className="p-4 flex-1">
                  <WidgetRenderer panel={panel} />
                </div>
              </div>
            ))}
          </div>
        )}
      </main>

      {/* ── CLIENT FOOTER FRAMING ───────────────────────────────── */}
      ${
        footerConfig.visible
          ? `<footer className="border-t border-zinc-800 bg-zinc-950 px-6 py-2.5 flex items-center justify-between text-xs text-zinc-400">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-emerald-500" />
          <span className="font-medium text-zinc-300">${footerConfig.statusLabel}</span>
          ${footerConfig.leftText ? `<span className="text-zinc-600">|</span><span>${footerConfig.leftText}</span>` : ''}
        </div>
        <div>${footerConfig.centerText}</div>
        <div>${footerConfig.rightText}</div>
      </footer>`
          : '/* Footer hidden */'
      }
    </div>
  )
}

function WidgetRenderer({ panel }: { panel: WidgetItem }) {
  if (panel.widgetType === 'empty') {
    return (
      <div className="w-full h-full min-h-[160px] rounded-xl border border-dashed border-zinc-800 bg-zinc-900/30 flex flex-col items-center justify-center p-6 text-center space-y-1">
        <span className="text-xs font-medium text-zinc-400">Empty Wireframe Slot</span>
        <span className="text-[11px] text-zinc-600 font-mono">Unassigned position in layout</span>
      </div>
    )
  }

  if (panel.widgetType === 'notes') {
    return (
      <div className="text-xs text-zinc-300 leading-relaxed whitespace-pre-line">
        {panel.widgetProps?.content || 'No directives recorded.'}
      </div>
    )
  }

  if (panel.widgetType === 'table') {
    const cols = panel.widgetProps?.columns || []
    const rows = panel.widgetProps?.rows || []
    return (
      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs text-zinc-300">
          <thead className="bg-zinc-800/60 text-zinc-400 text-[11px] uppercase border-b border-zinc-700/50">
            <tr>
              {cols.map((c: any) => (
                <th key={c.key} className="py-2.5 px-3 font-semibold">{c.header}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-zinc-800/40">
            {rows.map((r: any, idx: number) => (
              <tr key={idx} className="hover:bg-zinc-800/30 transition-colors">
                {cols.map((c: any) => (
                  <td key={c.key} className="py-2.5 px-3">{r[c.key]}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
  }

  if (panel.widgetType === 'aichat' || panel.widgetType === 'chat') {
    return (
      <div className="flex flex-col h-full min-h-[220px] text-xs">
        <div className="flex-1 space-y-2.5 overflow-y-auto mb-3">
          <div className="p-2.5 rounded-lg bg-zinc-800/80 border border-zinc-700/60 text-zinc-200">
            <span className="font-semibold text-indigo-400 block mb-1">Claude 3.7 Copilot</span>
            <p>Telemetry analyzed. 14 production clusters operational. All SLOs within healthy parameters.</p>
          </div>
          <div className="p-2.5 rounded-lg bg-indigo-600/30 border border-indigo-500/40 text-white ml-auto max-w-[85%]">
            <span className="font-semibold text-indigo-200 block mb-1">You</span>
            <p>Show active alerts and recommended remediation.</p>
          </div>
        </div>
        <div className="pt-2 border-t border-zinc-800 flex gap-2">
          <input
            type="text"
            placeholder="Ask AI Copilot..."
            disabled
            className="flex-1 bg-zinc-900 border border-zinc-800 rounded px-2.5 py-1 text-xs text-zinc-400"
          />
          <button disabled className="px-3 py-1 rounded bg-indigo-600/80 text-white text-xs font-semibold">
            Send
          </button>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'aiagent' || panel.widgetType === 'agent') {
    return (
      <div className="space-y-2 text-xs">
        <div className="p-2.5 rounded-lg bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between">
          <span className="font-medium text-zinc-200">1. Context & Telemetry Retrieval</span>
          <span className="text-[10px] text-emerald-400 font-mono">Completed (120ms)</span>
        </div>
        <div className="p-2.5 rounded-lg bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between">
          <span className="font-medium text-zinc-200">2. Tool: kubernetes_get_pod_status</span>
          <span className="text-[10px] text-emerald-400 font-mono">Completed (340ms)</span>
        </div>
        <div className="p-2.5 rounded-lg bg-indigo-950/30 border border-indigo-500/40 flex items-center justify-between text-indigo-200">
          <span className="font-medium">3. Autonomous CoT Synthesis</span>
          <span className="text-[10px] text-indigo-400 font-mono animate-pulse">Running</span>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'airag' || panel.widgetType === 'rag') {
    return (
      <div className="space-y-2 text-xs">
        <div className="p-2.5 rounded-lg bg-zinc-800/70 border border-zinc-700/60">
          <div className="flex justify-between text-[11px] mb-1">
            <span className="font-semibold text-zinc-200">SOC2_Compliance_Master_Policy.pdf</span>
            <span className="text-emerald-400 font-bold font-mono">98.4% Match</span>
          </div>
          <p className="text-[11px] text-zinc-400">All customer logs must be encrypted using AES-256 and purged after 90 days.</p>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'aiprompt' || panel.widgetType === 'prompt') {
    return (
      <div className="space-y-2 text-xs">
        <div className="p-2 rounded bg-zinc-900 border border-zinc-800 font-mono text-[11px] text-zinc-300">
          System Prompt: Enterprise Financial Copilot (Temperature: 0.35, Top-P: 0.90)
        </div>
        <div className="p-2 rounded bg-emerald-950/20 border border-emerald-500/30 text-emerald-300 text-[11px] font-mono">
          Benchmark: 215ms latency • 94.2 t/s • $0.0028/call
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'aicode' || panel.widgetType === 'code') {
    return (
      <div className="font-mono text-[11px] bg-zinc-950 p-2 rounded border border-zinc-800 space-y-1">
        <div className="text-rose-400 bg-rose-950/30 px-1 rounded">- private hmacSecret = process.env.JWT_SECRET;</div>
        <div className="text-emerald-400 bg-emerald-950/30 px-1 rounded">+ private publicKeyUrl = process.env.AUTH_JWKS_ENDPOINT;</div>
        <div className="text-emerald-400 bg-emerald-950/30 px-1 rounded">+ private ecdsaVerifier = new ES256TokenVerifier(this.publicKeyUrl);</div>
      </div>
    )
  }

  if (panel.widgetType === 'clock' || panel.widgetType === 'digitalclock' || panel.widgetType === 'worldclock') {
    return (
      <div className="flex flex-col items-center justify-center py-6 text-center">
        <div className="text-4xl font-extrabold font-mono text-white tracking-tight">13:58:25 PM</div>
        <div className="text-xs text-zinc-400 mt-1">Thursday, September 24, 2026 • EDT (UTC-4)</div>
        <div className="grid grid-cols-3 gap-2 mt-4 w-full">
          <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 text-center">
            <span className="text-[10px] text-zinc-400 block">London</span>
            <span className="text-xs font-mono font-bold text-indigo-300">18:58</span>
          </div>
          <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 text-center">
            <span className="text-[10px] text-zinc-400 block">Tokyo</span>
            <span className="text-xs font-mono font-bold text-indigo-300">02:58</span>
          </div>
          <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 text-center">
            <span className="text-[10px] text-zinc-400 block">San Francisco</span>
            <span className="text-xs font-mono font-bold text-indigo-300">10:58</span>
          </div>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'calendar' || panel.widgetType === 'agenda') {
    return (
      <div className="space-y-2 text-xs">
        <div className="font-semibold text-zinc-200 mb-1">September 2026 • Daily Agenda</div>
        <div className="p-2 rounded-lg bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between">
          <span className="font-medium text-zinc-200">10:00 AM • Sprint Review & Architecture Sync</span>
          <span className="w-2 h-2 rounded-full bg-indigo-400" />
        </div>
        <div className="p-2 rounded-lg bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between">
          <span className="font-medium text-zinc-200">02:30 PM • Client Deliverable Demo</span>
          <span className="w-2 h-2 rounded-full bg-emerald-400" />
        </div>
        <div className="p-2 rounded-lg bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between">
          <span className="font-medium text-zinc-200">04:15 PM • Kubernetes Mesh Patch Window</span>
          <span className="w-2 h-2 rounded-full bg-amber-400" />
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'pomodoro' || panel.widgetType === 'timer') {
    return (
      <div className="flex flex-col items-center justify-center py-4 text-center">
        <div className="text-4xl font-extrabold font-mono text-white tracking-tight">25:00</div>
        <div className="text-xs text-rose-400 font-medium mt-1">Focus Sprint (Session 2 of 4)</div>
        <div className="text-[11px] text-zinc-400 mt-2">Focusing on high-density architecture</div>
      </div>
    )
  }

  if (panel.widgetType === 'tasks' || panel.widgetType === 'todo') {
    return (
      <div className="space-y-1.5 text-xs">
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between">
          <span className="line-through text-zinc-500">✓ Review production cluster telemetry & APM logs</span>
          <span className="text-[9px] uppercase font-mono px-1 rounded bg-rose-500/20 text-rose-300">High</span>
        </div>
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between">
          <span className="line-through text-zinc-500">✓ Deploy automated SOC2 compliance retention policy</span>
          <span className="text-[9px] uppercase font-mono px-1 rounded bg-rose-500/20 text-rose-300">High</span>
        </div>
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between text-zinc-200">
          <span>□ Finalize enterprise client dashboard presentation</span>
          <span className="text-[9px] uppercase font-mono px-1 rounded bg-amber-500/20 text-amber-300">Medium</span>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'calculator' || panel.widgetType === 'calc') {
    return (
      <div className="p-3 bg-zinc-900 rounded-lg border border-zinc-800 text-center font-mono">
        <div className="text-xs text-zinc-500 text-right">1,250 × 1.2 = 1,500</div>
        <div className="text-2xl font-bold text-white text-right my-2">1,500</div>
        <div className="grid grid-cols-4 gap-1 text-xs">
          {['7', '8', '9', '÷', '4', '5', '6', '×', '1', '2', '3', '-', '0', '.', '=', '+'].map((k) => (
            <div key={k} className="p-1.5 rounded bg-zinc-800/60 text-zinc-200">{k}</div>
          ))}
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'weather') {
    return (
      <div className="space-y-3 text-xs">
        <div className="flex justify-between items-center">
          <div>
            <div className="text-3xl font-extrabold font-mono text-white">22°C</div>
            <div className="text-zinc-400">New York, US • Partly Cloudy</div>
          </div>
          <div className="text-right text-[11px] font-mono text-zinc-400">
            <div>High: 25°C • Low: 17°C</div>
            <div>Humidity: 48% • Wind: 14 km/h</div>
          </div>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'recorder' || panel.widgetType === 'meeting-record') {
    return (
      <div className="flex flex-col items-center justify-center py-4 text-center">
        <div className="text-3xl font-extrabold font-mono text-white tracking-tight">08:02</div>
        <div className="text-xs text-rose-400 font-medium mt-1 flex items-center gap-1.5">
          <span className="w-2 h-2 rounded-full bg-rose-500 animate-pulse" />
          <span>Recording Active • 256kbps Opus</span>
        </div>
        <div className="flex items-center gap-1 mt-3 h-6">
          {[20, 50, 80, 40, 90, 60, 30, 75, 45].map((h, i) => (
            <div key={i} className="w-1.5 bg-indigo-500 rounded-full" style={{ height: \`\${h}%\` }} />
          ))}
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'transcript' || panel.widgetType === 'meeting-transcript') {
    return (
      <div className="space-y-2 text-xs">
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60">
          <div className="flex justify-between text-[11px] font-mono mb-1">
            <span className="text-indigo-400 font-semibold">Sarah Lin (VP Eng)</span>
            <span className="text-zinc-500">10:14 AM</span>
          </div>
          <p className="text-zinc-300">Redis failover test was successful with zero dropped client packets.</p>
        </div>
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60">
          <div className="flex justify-between text-[11px] font-mono mb-1">
            <span className="text-emerald-400 font-semibold">Alex Chen (Staff Dev)</span>
            <span className="text-zinc-500">10:15 AM</span>
          </div>
          <p className="text-zinc-300">Enterprise cockpit export is locked for Friday deployment.</p>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'summary' || panel.widgetType === 'meeting-summary' || panel.widgetType === 'minutes') {
    return (
      <div className="p-3 bg-zinc-900 rounded-lg border border-zinc-800 text-xs text-zinc-300 space-y-2">
        <div className="font-semibold text-zinc-100 flex items-center justify-between">
          <span>AI Executive Minutes</span>
          <span className="text-[10px] font-mono text-indigo-400">Claude 3.7 Sonnet</span>
        </div>
        <p className="leading-relaxed">
          {panel.widgetProps?.tldr || 'Architecture sync confirmed Q3 cluster migration is green. Enterprise deliverable locked.'}
        </p>
      </div>
    )
  }

  if (panel.widgetType === 'meeting-actions') {
    return (
      <div className="space-y-1.5 text-xs">
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between">
          <span className="line-through text-zinc-500">✓ Merge Redis timeout patch (@Alex Chen)</span>
          <span className="text-[9px] font-mono text-emerald-400">Done</span>
        </div>
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 flex items-center justify-between text-zinc-200">
          <span>□ Package client dashboard release (@Sarah Lin)</span>
          <span className="text-[9px] font-mono text-amber-400">Due Thu</span>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'talk-time') {
    return (
      <div className="space-y-2.5 text-xs">
        <div>
          <div className="flex justify-between text-[11px] mb-1">
            <span className="text-zinc-300">Sarah Lin (VP Eng)</span>
            <span className="font-mono text-zinc-400">42% (138 wpm)</span>
          </div>
          <div className="h-1.5 w-full bg-zinc-800 rounded-full overflow-hidden">
            <div className="h-full bg-indigo-500 w-[42%]" />
          </div>
        </div>
        <div>
          <div className="flex justify-between text-[11px] mb-1">
            <span className="text-zinc-300">Alex Chen (Staff Dev)</span>
            <span className="font-mono text-zinc-400">36% (152 wpm)</span>
          </div>
          <div className="h-1.5 w-full bg-zinc-800 rounded-full overflow-hidden">
            <div className="h-full bg-emerald-500 w-[36%]" />
          </div>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'agenda-timer') {
    return (
      <div className="space-y-2 text-xs">
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 flex justify-between items-center text-zinc-400">
          <span>1. Redis failover verification</span>
          <span className="font-mono text-[10px]">14m / 15m (Done)</span>
        </div>
        <div className="p-2 rounded bg-indigo-950/30 border border-indigo-500/40 flex justify-between items-center text-white">
          <span>2. Enterprise dashboard review</span>
          <span className="font-mono text-[10px] text-indigo-300">12m / 20m (Active)</span>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'meeting-qa') {
    return (
      <div className="p-3 bg-zinc-900 rounded-lg border border-zinc-800 text-xs space-y-1.5">
        <div className="font-semibold text-zinc-200">Q: What did Sarah say about Friday?</div>
        <p className="text-zinc-300 pl-2 border-l-2 border-indigo-500">
          Sarah Lin confirmed delivery is strictly on schedule for Friday release.
        </p>
      </div>
    )
  }

  if (panel.widgetType === 'briefing') {
    return (
      <div className="space-y-2 text-xs">
        <div className="p-2 rounded bg-indigo-950/20 border border-indigo-500/30 text-zinc-200">
          <span className="text-[10px] font-mono text-indigo-400 block font-semibold">Objective</span>
          Demonstrate the 75+ client widget kit and confirm Friday release.
        </div>
        <div className="p-2 rounded bg-zinc-800/60 border border-zinc-700/60 flex justify-between items-center">
          <span className="text-zinc-200 font-medium">Sarah Lin (VP of Engineering)</span>
          <span className="text-[10px] text-zinc-500 font-mono">Acme Corp</span>
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'doc-markdown' || panel.widgetType === 'markdown' || panel.widgetType === 'md') {
    return (
      <div className="space-y-2 text-xs leading-relaxed">
        <div className="flex justify-between items-center pb-1.5 border-b border-zinc-800 text-[10px] font-mono text-zinc-400">
          <span className="text-indigo-400 font-semibold">{panel.widgetProps?.fileName || 'DOCUMENT.md'}</span>
          <span>4 min read • 1,280 words</span>
        </div>
        <h3 className="font-bold text-white text-sm">Enterprise Distributed Architecture RFC</h3>
        <p className="text-zinc-300">
          This RFC proposes migrating the legacy message bus to an event-driven stream architecture with zero-copy binary serialization.
        </p>
      </div>
    )
  }

  if (panel.widgetType === 'doc-pdf' || panel.widgetType === 'pdf') {
    return (
      <div className="p-3 bg-zinc-900/60 rounded-lg border border-zinc-800 flex flex-col items-center justify-center text-center space-y-2">
        <div className="text-xs font-semibold text-zinc-200">{panel.widgetProps?.fileName || 'Document_Report.pdf'}</div>
        <div className="w-full max-w-[200px] aspect-[3/4] bg-zinc-100 text-zinc-900 rounded shadow-md p-3 text-[9px] flex flex-col justify-between">
          <div className="font-bold text-left border-b border-zinc-400 pb-1">EXECUTIVE SUMMARY</div>
          <div className="text-left text-zinc-700 leading-tight">Audit completed with 100% compliance across all data stores.</div>
          <div className="text-right text-[8px] font-mono text-zinc-500">Page 3 of 18</div>
        </div>
        <div className="text-[10px] font-mono text-zinc-400">Scale: 100% • Vector PDF</div>
      </div>
    )
  }

  if (panel.widgetType === 'doc-docx' || panel.widgetType === 'docx') {
    return (
      <div className="p-3 bg-zinc-900/50 rounded-lg border border-zinc-800 space-y-2 text-xs">
        <div className="flex justify-between text-[10px] font-mono text-blue-400 border-b border-zinc-800 pb-1">
          <span>{panel.widgetProps?.fileName || 'Contract.docx'}</span>
          <span>Approved with Revisions</span>
        </div>
        <div className="font-bold text-white">MASTER SERVICES & PLATFORM SLA AGREEMENT</div>
        <p className="text-zinc-300 text-[11px] leading-relaxed">
          Provider agrees to deploy and maintain the customized Cockpit Application with 99.95% monthly SLA guarantee.
        </p>
      </div>
    )
  }

  if (panel.widgetType === 'doc-txt' || panel.widgetType === 'txt') {
    return (
      <div className="bg-zinc-950 p-2.5 rounded border border-zinc-800 font-mono text-[11px] space-y-1">
        <div className="text-zinc-500"># System Configuration Matrix</div>
        <div className="text-indigo-400">NODE_ENV=<span className="text-emerald-300">production</span></div>
        <div className="text-indigo-400">PORT=<span className="text-emerald-300">3920</span></div>
        <div className="text-indigo-400">ENCRYPTION=<span className="text-emerald-300">AES-256-GCM</span></div>
      </div>
    )
  }

  if (panel.widgetType === 'doc-diff' || panel.widgetType === 'diff') {
    return (
      <div className="space-y-1.5 font-mono text-[11px]">
        <div className="p-1 rounded bg-rose-950/30 border border-rose-500/30 text-rose-300">
          - Default user session idle expiration: 30 minutes
        </div>
        <div className="p-1 rounded bg-emerald-950/30 border border-emerald-500/30 text-emerald-200">
          + Default user session idle expiration: 15 minutes (SOC2 strict)
        </div>
        <div className="p-1 rounded bg-emerald-950/30 border border-emerald-500/30 text-emerald-200">
          + Mandatory hardware security key (FIDO2) required for admin tiers
        </div>
      </div>
    )
  }

  if (panel.widgetType === 'doc-code') {
    return (
      <div className="bg-zinc-950 p-2.5 rounded border border-zinc-800 font-mono text-[11px] text-zinc-300 space-y-1">
        <div className="text-zinc-500">// schema.prisma</div>
        <div className="text-indigo-300">model Tenant {'{'}</div>
        <div className="pl-3">id String @id @default(uuid())</div>
        <div className="pl-3">name String</div>
        <div className="text-indigo-300">{'}'}</div>
      </div>
    )
  }

  if (panel.widgetType === 'doc-csv' || panel.widgetType === 'csv') {
    return (
      <div className="overflow-x-auto text-[11px] font-mono">
        <table className="w-full text-left">
          <thead className="text-[10px] text-zinc-500 uppercase border-b border-zinc-800">
            <tr><th className="p-1">Client</th><th className="p-1">Tier</th><th className="p-1">MRR</th></tr>
          </thead>
          <tbody className="divide-y divide-zinc-800/40 text-zinc-300">
            <tr><td className="p-1">Acme Global</td><td className="p-1">Enterprise</td><td className="p-1 text-emerald-400">$45,000</td></tr>
            <tr><td className="p-1">Apex Fintech</td><td className="p-1">Enterprise</td><td className="p-1 text-emerald-400">$78,000</td></tr>
          </tbody>
        </table>
      </div>
    )
  }

  if (panel.widgetType === 'doc-summarizer' || panel.widgetType === 'doc-ai') {
    return (
      <div className="p-2.5 bg-indigo-950/20 border border-indigo-500/30 rounded text-xs space-y-1.5">
        <div className="font-semibold text-indigo-300">AI Document Summary</div>
        <p className="text-zinc-200 text-[11px]">
          Audit confirmed zero critical vulnerabilities across core infrastructure. Mandatory FIDO2 hardware tokens enforced.
        </p>
      </div>
    )
  }

  if (panel.widgetType === 'doc-metadata') {
    return (
      <div className="p-2 bg-zinc-900/60 rounded border border-zinc-800 font-mono text-[11px] space-y-1">
        <div className="flex justify-between text-zinc-400"><span>File:</span><span className="text-zinc-200">release-build.tar.gz</span></div>
        <div className="flex justify-between text-zinc-400"><span>SHA-256:</span><span className="text-emerald-400">e3b0c442...b855</span></div>
      </div>
    )
  }

  if (panel.widgetType === 'doc-reader' || panel.widgetType === 'focus-reader') {
    return (
      <div className="p-3 bg-[#1f1d19] text-[#e8dfd1] rounded border border-[#3b342a] text-xs space-y-2 font-serif">
        <h4 className="font-bold">The Evolution of High-Density App Shell Architectures</h4>
        <p className="text-[11px] leading-relaxed">
          Desktop software engineering is undergoing a quiet renaissance toward hyper-optimized standalone cockpits.
        </p>
      </div>
    )
  }

  if (panel.widgetType === 'doc-swagger' || panel.widgetType === 'swagger' || panel.widgetType === 'openapi') {
    return (
      <div className="p-2.5 bg-zinc-900/60 rounded border border-zinc-800 text-xs font-mono space-y-1.5">
        <div className="flex items-center gap-2">
          <span className="bg-blue-500/20 text-blue-300 px-1 rounded text-[10px] font-bold">GET</span>
          <span className="text-zinc-200">/v2/clusters</span>
        </div>
        <div className="text-[10px] text-zinc-400">Response: 200 OK (application/json)</div>
      </div>
    )
  }

  if (panel.widgetType === 'doc-contract' || panel.widgetType === 'contract') {
    return (
      <div className="p-2.5 bg-zinc-900/60 rounded border border-zinc-800 text-xs space-y-1.5">
        <div className="flex justify-between font-semibold">
          <span className="text-zinc-200">MSA-2026-Q3</span>
          <span className="text-emerald-400 font-mono text-[10px]">Signed & Executed</span>
        </div>
        <p className="text-zinc-300 text-[11px]">All stakeholder approvals completed and archived.</p>
      </div>
    )
  }

  return (
    <div className="py-8 text-center text-xs text-zinc-500 italic">
      [Live widget container: {panel.title}]
    </div>
  )
}

export default ClientDashboard
`
}
