import type { HeaderConfig, FooterConfig, PanelConfig } from '../types/reframe-types'
import { FONT_MAP } from '../types/reframe-types'

export interface CodegenOptions {
  templateName: string
  headerConfig: HeaderConfig
  footerConfig: FooterConfig
  panels: Record<string, PanelConfig>
  themeKey?: string
}

/**
 * Generates a standalone, production-ready React TSX component
 * that renders the client deliverable using pure Tailwind CSS Grid.
 * Contains ZERO dependencies on Dockview, sashes, or builder chrome.
 */
export function generateStandaloneClientTsx(options: CodegenOptions): string {
  const { templateName, headerConfig, footerConfig, panels } = options

  const panelList = Object.values(panels)
  const fontFamily = FONT_MAP[headerConfig.fontFamily] || FONT_MAP.inter

  // Format panel data as clean JSON to embed directly in the component
  const embeddedPanelsJson = JSON.stringify(panelList, null, 2)

  return `import React, { useState } from 'react'
import {
  Layers,
  Activity,
  BarChart3,
  Terminal,
  Sparkles,
  Shield,
  Zap,
  RefreshCw,
  Search,
  ArrowUpRight,
  TrendingUp,
  TrendingDown,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Info
} from 'lucide-react'
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid
} from 'recharts'

/**
 * =====================================================================
 * CLIENT DELIVERABLE: ${templateName.toUpperCase()}
 * Generated by Reframe Studio
 * Pure React + Tailwind CSS (Zero Dockview Runtime)
 * =====================================================================
 */

interface WidgetItem {
  id: string
  title: string
  widgetType: 'kpi' | 'chart' | 'table' | 'notes' | 'activity' | 'actionpad' | 'embed' | 'terminal' | 'cluster'
  widgetProps: Record<string, any>
}

const BAKED_PANELS: WidgetItem[] = ${embeddedPanelsJson}

export const ClientDashboard: React.FC = () => {
  const [activeTab, setActiveTab] = useState<string>('all')

  return (
    <div
      className="w-full min-h-screen bg-zinc-950 text-zinc-100 flex flex-col font-sans select-none"
      style={{ fontFamily: '${fontFamily}' }}
    >
      {/* ── CLIENT HEADER FRAMING ───────────────────────────────── */}
      ${
        headerConfig.visible
          ? `<header className="border-b border-zinc-800 bg-zinc-950/90 backdrop-blur-md px-6 py-3 flex items-center justify-between gap-4 sticky top-0 z-30">
        <div className="flex items-center gap-3 min-w-0">
          ${
            headerConfig.showLogo
              ? `<div className="w-8 h-8 rounded-lg bg-indigo-600/20 border border-indigo-500/40 flex items-center justify-center text-indigo-400 shrink-0">
            <Layers className="w-4 h-4" />
          </div>`
              : ''
          }
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-bold tracking-tight text-white">${headerConfig.title}</h1>
              ${
                headerConfig.badge
                  ? `<span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/30">
                ${headerConfig.badge}
              </span>`
                  : ''
              }
            </div>
            ${headerConfig.subtitle ? `<p className="text-xs text-zinc-400 font-normal">${headerConfig.subtitle}</p>` : ''}
          </div>
        </div>

        <div className="flex items-center gap-2">
          ${headerConfig.actions
            .map(
              (act) => `
          <button
            key="${act.id}"
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-900 border border-zinc-800 hover:border-zinc-700 text-zinc-200 transition-colors"
          >
            <span>${act.label}</span>
          </button>`
            )
            .join('')}
        </div>
      </header>`
          : '/* Header hidden */'
      }

      {/* ── MAIN DASHBOARD GRID (ZERO DOCKVIEW) ──────────────────── */}
      <main className="flex-1 p-6 overflow-y-auto space-y-6 max-w-7xl mx-auto w-full">
        {/* KPI Strip */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {BAKED_PANELS.filter(p => p.widgetType === 'kpi').map(panel => (
            panel.widgetProps?.items?.map((item: any, idx: number) => (
              <div
                key={idx}
                className="p-4 rounded-xl bg-zinc-900/60 border border-zinc-800/80 hover:border-zinc-700 transition-all flex flex-col justify-between shadow-sm"
              >
                <div className="flex items-center justify-between text-xs text-zinc-400 mb-2">
                  <span>{item.label}</span>
                  {item.delta && (
                    <span className="inline-flex items-center gap-0.5 px-2 py-0.5 rounded text-[11px] font-medium bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                      {item.delta}
                    </span>
                  )}
                </div>
                <div className="text-2xl font-bold text-white tracking-tight">{item.value}</div>
                {item.subtext && <div className="text-[11px] text-zinc-500 mt-1">{item.subtext}</div>}
              </div>
            ))
          ))}
        </div>

        {/* Primary Content Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {BAKED_PANELS.filter(p => p.widgetType !== 'kpi').map(panel => {
            const isLarge = panel.widgetType === 'chart' || panel.widgetType === 'table' || panel.widgetType === 'embed'
            const colSpan = isLarge ? 'lg:col-span-8' : 'lg:col-span-4'

            return (
              <div
                key={panel.id}
                className={\`\${colSpan} rounded-xl bg-zinc-900/50 border border-zinc-800/80 overflow-hidden shadow-sm flex flex-col\`}
              >
                <div className="px-4 py-3 border-b border-zinc-800 flex items-center justify-between bg-zinc-900/80">
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-indigo-500" />
                    <h2 className="text-sm font-semibold text-zinc-100">{panel.title}</h2>
                  </div>
                  <span className="text-[10px] uppercase font-mono tracking-wider text-zinc-500 px-2 py-0.5 rounded bg-zinc-800/60">
                    {panel.widgetType}
                  </span>
                </div>
                <div className="p-4 flex-1">
                  <WidgetRenderer panel={panel} />
                </div>
              </div>
            )
          })}
        </div>
      </main>

      {/* ── CLIENT FOOTER FRAMING ───────────────────────────────── */}
      ${
        footerConfig.visible
          ? `<footer className="border-t border-zinc-800 bg-zinc-950 px-6 py-2.5 flex items-center justify-between text-xs text-zinc-400">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-emerald-500" />
          <span className="font-medium text-zinc-300">${footerConfig.statusLabel}</span>
          ${footerConfig.leftText ? `<span className="text-zinc-600">|</span><span>${footerConfig.leftText}</span>` : ''}
        </div>
        <div>${footerConfig.centerText}</div>
        <div>${footerConfig.rightText}</div>
      </footer>`
          : '/* Footer hidden */'
      }
    </div>
  )
}

function WidgetRenderer({ panel }: { panel: WidgetItem }) {
  if (panel.widgetType === 'notes') {
    return (
      <div className="text-xs text-zinc-300 leading-relaxed whitespace-pre-line">
        {panel.widgetProps?.content || 'No directives recorded.'}
      </div>
    )
  }

  if (panel.widgetType === 'table') {
    const cols = panel.widgetProps?.columns || []
    const rows = panel.widgetProps?.rows || []
    return (
      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs text-zinc-300">
          <thead className="bg-zinc-800/60 text-zinc-400 text-[11px] uppercase border-b border-zinc-700/50">
            <tr>
              {cols.map((c: any) => (
                <th key={c.key} className="py-2.5 px-3 font-semibold">{c.header}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-zinc-800/40">
            {rows.map((r: any, idx: number) => (
              <tr key={idx} className="hover:bg-zinc-800/30 transition-colors">
                {cols.map((c: any) => (
                  <td key={c.key} className="py-2.5 px-3">{r[c.key]}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
  }

  return (
    <div className="py-8 text-center text-xs text-zinc-500 italic">
      [Live widget container: {panel.title}]
    </div>
  )
}

export default ClientDashboard
`
}
