import type { HeaderConfig, FooterConfig, PanelConfig } from '../types/reframe-types'
import { FONT_MAP } from '../types/reframe-types'

export interface CodegenOptions {
  templateName: string
  headerConfig: HeaderConfig
  footerConfig: FooterConfig
  panels: Record<string, PanelConfig>
  themeKey?: string
  layoutJson?: any
}

/**
 * Generates a standalone, production-ready React TSX component
 * that renders the client deliverable using pure Tailwind CSS Flex/Grid.
 * Faithfully reproduces the Dockview layout tree with ZERO dependencies
 * on Dockview, sashes, or builder chrome.
 */
export function generateStandaloneClientTsx(options: CodegenOptions): string {
  const { templateName, headerConfig, footerConfig, panels, layoutJson } = options

  const panelList = Object.values(panels)
  const fontFamily = FONT_MAP[headerConfig.fontFamily] || FONT_MAP.inter

  // Format panel data and layout tree as clean JSON to embed directly in the component
  const embeddedPanelsJson = JSON.stringify(panelList, null, 2)
  const embeddedGridJson = layoutJson?.grid?.root
    ? JSON.stringify(layoutJson.grid, null, 2)
    : 'null'

  return `import React, { useState } from 'react'
import {
  Layers,
  Activity,
  BarChart3,
  Terminal,
  Sparkles,
  Shield,
  Zap,
  RefreshCw,
  Search,
  ArrowUpRight,
  TrendingUp,
  TrendingDown,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Info
} from 'lucide-react'
import {
  ResponsiveContainer,
  AreaChart,
  Area,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid
} from 'recharts'

/**
 * =====================================================================
 * CLIENT DELIVERABLE: ${templateName.toUpperCase()}
 * Generated by Reframe Studio
 * Pure React + Tailwind CSS (Zero Dockview Runtime)
 * =====================================================================
 */

interface WidgetItem {
  id: string
  title: string
  widgetType: 'kpi' | 'chart' | 'table' | 'notes' | 'activity' | 'actionpad' | 'embed' | 'terminal' | 'cluster' | 'empty'
  widgetProps: Record<string, any>
}

const BAKED_PANELS: WidgetItem[] = ${embeddedPanelsJson}
const LAYOUT_GRID: any = ${embeddedGridJson}

function DockviewNodeRenderer({ node, orientation }: { node: any; orientation: 'HORIZONTAL' | 'VERTICAL' }) {
  if (!node) return null

  if (node.type === 'leaf') {
    const activeViewId = node.data?.activeView || (node.data?.views && node.data.views[0])
    const panel = BAKED_PANELS.find((p) => p.id === activeViewId)
    if (!panel) return null

    return (
      <div className="w-full h-full rounded-xl bg-zinc-900/50 border border-zinc-800/80 overflow-hidden shadow-sm flex flex-col hover:border-zinc-700/80 transition-all backdrop-blur-sm min-h-[220px]">
        <div className="px-4 py-3 border-b border-zinc-800 flex items-center justify-between bg-zinc-900/80 shrink-0">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-indigo-500" />
            <h2 className="text-sm font-semibold text-zinc-100">{panel.title}</h2>
          </div>
          <span className="text-[10px] uppercase font-mono tracking-wider text-zinc-500 px-2 py-0.5 rounded bg-zinc-800/60">
            {panel.widgetType}
          </span>
        </div>
        <div className="p-4 flex-1 overflow-auto">
          <WidgetRenderer panel={panel} />
        </div>
      </div>
    )
  }

  if (node.type === 'branch') {
    const isHorizontal = orientation === 'HORIZONTAL'
    const nextOrientation = isHorizontal ? 'VERTICAL' : 'HORIZONTAL'
    const children = Array.isArray(node.data) ? node.data : []

    return (
      <div className={\`w-full h-full flex gap-4 min-w-0 min-h-0 \${isHorizontal ? 'flex-col md:flex-row' : 'flex-col'}\`}>
        {children.map((child: any, idx: number) => {
          const flexGrow = typeof child.size === 'number' && child.size > 0 ? child.size : 1
          return (
            <div key={idx} className="flex-1 min-w-0 min-h-0 flex flex-col" style={{ flex: \`\${flexGrow} 1 0%\` }}>
              <DockviewNodeRenderer node={child} orientation={nextOrientation} />
            </div>
          )
        })}
      </div>
    )
  }

  return null
}

export const ClientDashboard: React.FC = () => {
  return (
    <div
      className="w-full min-h-screen bg-zinc-950 text-zinc-100 flex flex-col font-sans select-none"
      style={{ fontFamily: '${fontFamily}' }}
    >
      {/* ── CLIENT HEADER FRAMING ───────────────────────────────── */}
      ${
        headerConfig.visible
          ? `<header className="border-b border-zinc-800 bg-zinc-950/90 backdrop-blur-md px-6 py-3 flex items-center justify-between gap-4 sticky top-0 z-30">
        <div className="flex items-center gap-3 min-w-0">
          ${
            headerConfig.showLogo
              ? `<div className="w-8 h-8 rounded-lg bg-indigo-600/20 border border-indigo-500/40 flex items-center justify-center text-indigo-400 shrink-0">
            <Layers className="w-4 h-4" />
          </div>`
              : ''
          }
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl font-bold tracking-tight text-white">${headerConfig.title}</h1>
              ${
                headerConfig.badge
                  ? `<span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-indigo-500/10 text-indigo-400 border border-indigo-500/30">
                ${headerConfig.badge}
              </span>`
                  : ''
              }
            </div>
            ${headerConfig.subtitle ? `<p className="text-xs text-zinc-400 font-normal">${headerConfig.subtitle}</p>` : ''}
          </div>
        </div>

        <div className="flex items-center gap-2">
          ${headerConfig.actions
            .map(
              (act) => `
          <button
            key="${act.id}"
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium bg-zinc-900 border border-zinc-800 hover:border-zinc-700 text-zinc-200 transition-colors"
          >
            <span>${act.label}</span>
          </button>`
            )
            .join('')}
        </div>
      </header>`
          : '/* Header hidden */'
      }

      {/* ── MAIN DASHBOARD GRID (ZERO DOCKVIEW) ──────────────────── */}
      <main className="flex-1 p-6 overflow-y-auto max-w-7xl mx-auto w-full flex flex-col min-h-0">
        {LAYOUT_GRID?.root ? (
          <div className="w-full h-full min-h-0 flex-1 flex flex-col">
            <DockviewNodeRenderer node={LAYOUT_GRID.root} orientation={LAYOUT_GRID.orientation || 'HORIZONTAL'} />
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 flex-1">
            {BAKED_PANELS.map((panel) => (
              <div
                key={panel.id}
                className="rounded-xl bg-zinc-900/50 border border-zinc-800/80 overflow-hidden shadow-sm flex flex-col"
              >
                <div className="px-4 py-3 border-b border-zinc-800 flex items-center justify-between bg-zinc-900/80">
                  <div className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-indigo-500" />
                    <h2 className="text-sm font-semibold text-zinc-100">{panel.title}</h2>
                  </div>
                  <span className="text-[10px] uppercase font-mono tracking-wider text-zinc-500 px-2 py-0.5 rounded bg-zinc-800/60">
                    {panel.widgetType}
                  </span>
                </div>
                <div className="p-4 flex-1">
                  <WidgetRenderer panel={panel} />
                </div>
              </div>
            ))}
          </div>
        )}
      </main>

      {/* ── CLIENT FOOTER FRAMING ───────────────────────────────── */}
      ${
        footerConfig.visible
          ? `<footer className="border-t border-zinc-800 bg-zinc-950 px-6 py-2.5 flex items-center justify-between text-xs text-zinc-400">
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-emerald-500" />
          <span className="font-medium text-zinc-300">${footerConfig.statusLabel}</span>
          ${footerConfig.leftText ? `<span className="text-zinc-600">|</span><span>${footerConfig.leftText}</span>` : ''}
        </div>
        <div>${footerConfig.centerText}</div>
        <div>${footerConfig.rightText}</div>
      </footer>`
          : '/* Footer hidden */'
      }
    </div>
  )
}

function WidgetRenderer({ panel }: { panel: WidgetItem }) {
  if (panel.widgetType === 'empty') {
    return (
      <div className="w-full h-full min-h-[160px] rounded-xl border border-dashed border-zinc-800 bg-zinc-900/30 flex flex-col items-center justify-center p-6 text-center space-y-1">
        <span className="text-xs font-medium text-zinc-400">Empty Wireframe Slot</span>
        <span className="text-[11px] text-zinc-600 font-mono">Unassigned position in layout</span>
      </div>
    )
  }

  if (panel.widgetType === 'notes') {
    return (
      <div className="text-xs text-zinc-300 leading-relaxed whitespace-pre-line">
        {panel.widgetProps?.content || 'No directives recorded.'}
      </div>
    )
  }

  if (panel.widgetType === 'table') {
    const cols = panel.widgetProps?.columns || []
    const rows = panel.widgetProps?.rows || []
    return (
      <div className="overflow-x-auto">
        <table className="w-full text-left text-xs text-zinc-300">
          <thead className="bg-zinc-800/60 text-zinc-400 text-[11px] uppercase border-b border-zinc-700/50">
            <tr>
              {cols.map((c: any) => (
                <th key={c.key} className="py-2.5 px-3 font-semibold">{c.header}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-zinc-800/40">
            {rows.map((r: any, idx: number) => (
              <tr key={idx} className="hover:bg-zinc-800/30 transition-colors">
                {cols.map((c: any) => (
                  <td key={c.key} className="py-2.5 px-3">{r[c.key]}</td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
  }

  return (
    <div className="py-8 text-center text-xs text-zinc-500 italic">
      [Live widget container: {panel.title}]
    </div>
  )
}

export default ClientDashboard
`
}
